# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3   # プロジェクトの Ruby バージョンに合わせる
          bundler-cache: true

      - name: Install required Bundler version
        run: |
          required=$(ruby -e "puts File.read('Gemfile.lock')[/\n\nBUNDLED WITH\n +([^\n]+)/, 1]")
          echo "Installing Bundler $required"
          gem install bundler -v "$required"

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop --force

      # Linter / Security
      - name: Security audit dependencies
        run: bin/bundler-audit --update

      - name: Security audit application code
        run: bin/brakeman -q -w2

      - name: Lint Ruby files
        run: bin/rubocop --parallel
